export const ONBOARDING_TEMPLATE_RECORD_TYPES = [
  'unit',
  'member',
  'committee',
  'committeeMembership',
  'roleAssignment',
  'document',
  'event',
  'announcement',
  'maintenanceRequest',
] as const;

export type OnboardingTemplateRecordType = typeof ONBOARDING_TEMPLATE_RECORD_TYPES[number];

export const ONBOARDING_TEMPLATE_COLUMNS = [
  'recordType',
  'unitNumber',
  'buildingName',
  'floor',
  'unitType',
  'unitStatus',
  'firstName',
  'lastName',
  'email',
  'phone',
  'memberStatus',
  'moveInDate',
  'appRole',
  'emergencyContactName',
  'emergencyContactPhone',
  'parkingStall',
  'storageLocker',
  'committeeName',
  'committeeDescription',
  'committeeChairEmail',
  'committeeRole',
  'documentTitle',
  'documentCategory',
  'documentUrl',
  'documentFileType',
  'documentAuthor',
  'documentDate',
  'documentTags',
  'documentVisibility',
  'eventTitle',
  'eventDate',
  'eventTime',
  'eventLocation',
  'eventCategory',
  'eventDescription',
  'announcementTitle',
  'announcementContent',
  'announcementType',
  'announcementPriority',
  'announcementDate',
  'maintenanceTitle',
  'maintenanceDescription',
  'maintenancePriority',
  'maintenanceCategory',
  'maintenanceStatus',
  'requestedByEmail',
  'notes',
] as const;

export type OnboardingTemplateColumn = typeof ONBOARDING_TEMPLATE_COLUMNS[number];
export type OnboardingTemplateRow = Record<OnboardingTemplateColumn, string>;

const csvEscape = (value: string | number) => {
  const text = String(value);
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
};

const row = (
  recordType: OnboardingTemplateRecordType,
  values: Partial<Record<OnboardingTemplateColumn, string>>,
): OnboardingTemplateRow => ({
  recordType,
  unitNumber: '',
  buildingName: '',
  floor: '',
  unitType: '',
  unitStatus: '',
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  memberStatus: '',
  moveInDate: '',
  appRole: '',
  emergencyContactName: '',
  emergencyContactPhone: '',
  parkingStall: '',
  storageLocker: '',
  committeeName: '',
  committeeDescription: '',
  committeeChairEmail: '',
  committeeRole: '',
  documentTitle: '',
  documentCategory: '',
  documentUrl: '',
  documentFileType: '',
  documentAuthor: '',
  documentDate: '',
  documentTags: '',
  documentVisibility: '',
  eventTitle: '',
  eventDate: '',
  eventTime: '',
  eventLocation: '',
  eventCategory: '',
  eventDescription: '',
  announcementTitle: '',
  announcementContent: '',
  announcementType: '',
  announcementPriority: '',
  announcementDate: '',
  maintenanceTitle: '',
  maintenanceDescription: '',
  maintenancePriority: '',
  maintenanceCategory: '',
  maintenanceStatus: '',
  requestedByEmail: '',
  notes: '',
  ...values,
});

const sampleRows: OnboardingTemplateRow[] = [
  row('unit', {
    unitNumber: '101',
    buildingName: 'Main Building',
    floor: '1',
    unitType: '1BR',
    unitStatus: 'Vacant',
    notes: 'Create units before importing members.',
  }),
  row('member', {
    unitNumber: '101',
    firstName: 'Ada',
    lastName: 'Lovelace',
    email: 'ada@example.com',
    phone: '250-000-0000',
    memberStatus: 'Current',
    moveInDate: '2026-01-15',
    appRole: 'MEMBER',
  }),
  row('committee', {
    committeeName: 'Finance Committee',
    committeeDescription: 'Budget, reserves, and financial reporting.',
    committeeChairEmail: 'ada@example.com',
    notes: 'Create committee spaces before assigning committee memberships.',
  }),
  row('committeeMembership', {
    email: 'ada@example.com',
    committeeName: 'Finance Committee',
    committeeRole: 'Chair',
  }),
  row('roleAssignment', {
    email: 'grace@example.com',
    appRole: 'BOARD',
    notes: 'Supported app roles today: ADMIN, BOARD, MEMBER.',
  }),
  row('document', {
    committeeName: 'Finance Committee',
    documentTitle: 'Operating Rules',
    documentCategory: 'Policy',
    documentUrl: 'https://example.com/operating-rules.pdf',
    documentFileType: 'pdf',
    documentAuthor: 'Admin',
    documentDate: '2026-01-20',
    documentTags: 'Policy, Governance',
    documentVisibility: 'MEMBERS',
  }),
  row('event', {
    committeeName: 'Finance Committee',
    eventTitle: 'Monthly Finance Meeting',
    eventDate: '2026-02-10',
    eventTime: '18:30',
    eventLocation: 'Common Room',
    eventCategory: 'Committee',
    eventDescription: 'Review monthly financial package.',
  }),
  row('announcement', {
    announcementTitle: 'Welcome to coopHUB',
    announcementContent: 'The workspace is ready for member onboarding.',
    announcementType: 'General',
    announcementPriority: 'Medium',
    announcementDate: '2026-01-25',
  }),
  row('maintenanceRequest', {
    unitNumber: '101',
    maintenanceTitle: 'Kitchen faucet leak',
    maintenanceDescription: 'Slow drip under kitchen sink.',
    maintenancePriority: 'Medium',
    maintenanceCategory: 'Plumbing',
    maintenanceStatus: 'Pending',
    requestedByEmail: 'ada@example.com',
  }),
];

export const buildOnboardingTemplateCsv = () =>
  [
    ONBOARDING_TEMPLATE_COLUMNS,
    ...sampleRows.map(templateRow => ONBOARDING_TEMPLATE_COLUMNS.map(column => templateRow[column])),
  ]
    .map(cells => cells.map(csvEscape).join(','))
    .join('\n');
